language: go
sudo: required
install: true
go:
  - 1.7
env:
  global:
    - GOARCH=amd64
before_script:
  - go vet ./...
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true